### ISSUE TITLE
[Bug]: Crawl4ai is not updated to the latest playwright-stealth release

### ISSUE THREAD

**Issue by charliedelta02** [unclecode/crawl4ai#1273]
### crawl4ai version

0.6.3

### Expected Behavior

Crawl4AI should work with the latest version of playwright-stealth.

### Current Behavior

The playwright-stealth package has been updated to version `2.0.0` and has significant changes to the input contract.
If playwright-stealth is updated to the latest version, then Crawl4AI will through the following exception:
```
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from .async_crawler_strategy import
from .browser_manager import BrowserManager
from playwright_stealth import StealthConfig
E   ImportError: cannot import name 'StealthConfig' from 'playwright_stealth' 
```

The latest version will only work with playwright-stealth version `1.0.6`.

### Is this reproducible?

Yes

### Inputs Causing the Bug

```bash
- Settings used: Update playwright-stealth to version 2.0.0
```

### Steps to Reproduce

```bash
1. Update playwright-stealth to version 2.0.0
2. Run crawl4ai script to observe the exception
```

### Code snippets

```python

```

### OS

macOS, Linux

### Python version

3.12

### Browser

Chrome

### Browser version

138.0.0.0

### Error logs & Screenshots (if applicable)

```
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
from .async_crawler_strategy import
from .browser_manager import BrowserManager
from playwright_stealth import StealthConfig
E   ImportError: cannot import name 'StealthConfig' from 'playwright_stealth' 
```

**Comment by huaihaochuan** [comment]
same issue here
